### ISSUE TITLE
Package failing tests in Jest due to Error: Uncaught [TypeError: Cannot set property 'imageSmoothingEnabled' of null]

### ISSUE THREAD

**Issue by TheGameKnave** [tuhnik/react-identicons#5]
Adding this package to my project causes my tests to fail with:

    Error: Uncaught [TypeError: Cannot set property 'imageSmoothingEnabled' of null]

Seems to be related to ~line 46 in the source.

````
 FAIL  src/__tests__/PostEditForm.js
  ● Console

    console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
          at module.exports (/Users/Websites/eval/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
          at HTMLCanvasElementImpl.getContext (/Users/Websites/eval/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
          at HTMLCanvasElement.getContext (/Users/Websites/eval/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:50:45)
          at e.value (/Users/Websites/eval/node_modules/react-identicons/build/index.js:1:2775)
          at e.value (/Users/Websites/eval/node_modules/react-identicons/build/index.js:1:2152)
          at commitLifeCycles (/Users/Websites/eval/node_modules/react-dom/cjs/react-dom.development.js:17334:22)
          at commitAllLifeCycles (/Users/Websites/eval/node_modules/react-dom/cjs/react-dom.development.js:18736:7)
          at HTMLUnknownElement.callCallback (/Users/Websites/eval/node_modules/react-dom/cjs/react-dom.development.js:149:14)
          at invokeEventListeners (/Users/Websites/eval/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
          at HTMLUnknownElementImpl._dispatch (/Users/Websites/eval/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9) undefined
    console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Uncaught [TypeError: Cannot set property 'imageSmoothingEnabled' of null]
          at reportException (/Users/Websites/eval/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
          at invokeEventListeners (/Users/Websites/eval/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
          at HTMLUnknownElementImpl._dispatch (/Users/Websites/eval/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/Websites/eval/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/Websites/eval/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
          at HTMLUnknownElement.dispatchEvent (/Users/Websites/eval/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
          at Object.invokeGuardedCallbackDev (/Users/Websites/eval/node_modules/react-dom/cjs/react-dom.development.js:199:16)
          at invokeGuardedCallback (/Users/Websites/eval/node_modules/react-dom/cjs/react-dom.development.js:256:31)
          at commitRoot (/Users/Websites/eval/node_modules/react-dom/cjs/react-dom.development.js:18948:7)
          at /Users/Websites/eval/node_modules/react-dom/cjs/react-dom.development.js:20418:5 TypeError: Cannot set property 'imageSmoothingEnabled' of null
          at e.value (/Users/Websites/eval/node_modules/react-identicons/build/index.js:1:2815)
          at e.value (/Users/Websites/eval/node_modules/react-identicons/build/index.js:1:2152)
          at commitLifeCycles (/Users/Websites/eval/node_modules/react-dom/cjs/react-dom.development.js:17334:22)
          at commitAllLifeCycles (/Users/Websites/eval/node_modules/react-dom/cjs/react-dom.development.js:18736:7)
          at HTMLUnknownElement.callCallback (/Users/Websites/eval/node_modules/react-dom/cjs/react-dom.development.js:149:14)
          at invokeEventListeners (/Users/Websites/eval/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
          at HTMLUnknownElementImpl._dispatch (/Users/Websites/eval/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/Websites/eval/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/Websites/eval/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
          at HTMLUnknownElement.dispatchEvent (/Users/Websites/eval/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
          at Object.invokeGuardedCallbackDev (/Users/Websites/eval/node_modules/react-dom/cjs/react-dom.development.js:199:16)
          at invokeGuardedCallback (/Users/Websites/eval/node_modules/react-dom/cjs/react-dom.development.js:256:31)
          at commitRoot (/Users/Websites/eval/node_modules/react-dom/cjs/react-dom.development.js:18948:7)
          at /Users/Websites/eval/node_modules/react-dom/cjs/react-dom.development.js:20418:5
          at Object.unstable_runWithPriority (/Users/Websites/eval/node_modules/scheduler/cjs/scheduler.development.js:255:12)
          at completeRoot (/Users/Websites/eval/node_modules/react-dom/cjs/react-dom.development.js:20417:13)
          at performWorkOnRoot (/Users/Websites/eval/node_modules/react-dom/cjs/react-dom.development.js:20346:9)
          at performWork (/Users/Websites/eval/node_modules/react-dom/cjs/react-dom.development.js:20254:7)
          at performSyncWork (/Users/Websites/eval/node_modules/react-dom/cjs/react-dom.development.js:20228:3)
          at Object.batchedUpdates$1 [as unstable_batchedUpdates] (/Users/Websites/eval/node_modules/react-dom/cjs/react-dom.development.js:20443:7)
          at Object.act (/Users/Websites/eval/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1161:27)
          at act (/Users/Websites/eval/node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:346:13)
          at Object.wrapAct [as render] (/Users/Websites/eval/node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:415:16)
          at new render (/Users/Websites/eval/node_modules/enzyme/src/ReactWrapper.js:115:16)
          at mount (/Users/Websites/eval/node_modules/enzyme/src/mount.js:10:10)
          at Suite.Object.<anonymous>.describe (/Users/Websites/eval/src/__tests__/PostEditForm.js:25:19)
          at addSpecsToSuite (/Users/Websites/eval/node_modules/jest-jasmine2/build/jasmine/Env.js:496:51)
          at Env.describe (/Users/Websites/eval/node_modules/jest-jasmine2/build/jasmine/Env.js:466:11)
          at describe (/Users/Websites/eval/node_modules/jest-jasmine2/build/jasmine/jasmineLight.js:81:18)
          at Object.describe (/Users/Websites/eval/src/__tests__/PostEditForm.js:18:1)
          at Runtime._execModule (/Users/Websites/eval/node_modules/jest-runtime/build/index.js:888:13)
          at Runtime._loadModule (/Users/Websites/eval/node_modules/jest-runtime/build/index.js:577:12)
          at Runtime.requireModule (/Users/Websites/eval/node_modules/jest-runtime/build/index.js:433:10)
          at /Users/Websites/eval/node_modules/jest-jasmine2/build/index.js:201:13
          at Generator.next (<anonymous>)
          at asyncGeneratorStep (/Users/Websites/eval/node_modules/jest-jasmine2/build/index.js:27:24)
          at _next (/Users/Websites/eval/node_modules/jest-jasmine2/build/index.js:47:9)
          at /Users/Websites/eval/node_modules/jest-jasmine2/build/index.js:52:7
          at new Promise (<anonymous>)
          at /Users/Websites/eval/node_modules/jest-jasmine2/build/index.js:44:12
          at _jasmine (/Users/Websites/eval/node_modules/jest-jasmine2/build/index.js:206:19)
          at jasmine2 (/Users/Websites/eval/node_modules/jest-jasmine2/build/index.js:60:19)
          at /Users/Websites/eval/node_modules/jest-runner/build/runTest.js:385:24
          at Generator.next (<anonymous>)
          at asyncGeneratorStep (/Users/Websites/eval/node_modules/jest-runner/build/runTest.js:161:24)
          at _next (/Users/Websites/eval/node_modules/jest-runner/build/runTest.js:181:9)
          at processTicksAndRejections (internal/process/task_queues.js:86:5)
    console.error node_modules/react-dom/cjs/react-dom.development.js:17117
      The above error occurred in the <e> component:
          in e (at PostEditForm.js:117)
          in h2 (at PostEditForm.js:116)
          in form (at PostEditForm.js:115)
          in PostEditForm (created by ConnectFunction)
          in ConnectFunction (at PostEditForm.js:22)
          in Provider (created by WrapperComponent)
          in WrapperComponent
      
      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

  ● components/PostEditForm: › encountered a declaration exception

    TypeError: Cannot set property 'imageSmoothingEnabled' of null

      23 |         </Provider>
      24 |     );
    > 25 |     let wrapper = mount(component(store));
         |                   ^
      26 |     let postEditForm = wrapper.find('PostEditForm');
      27 | 
      28 |     it('should render correctly with required props', () => {

      at e.value (node_modules/react-identicons/build/index.js:1:2815)
      at e.value (node_modules/react-identicons/build/index.js:1:2152)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:17334:22)
      at commitAllLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:18736:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:149:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:199:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:256:31)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:18948:7)
      at node_modules/react-dom/cjs/react-dom.development.js:20418:5
      at Object.unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:255:12)
      at completeRoot (node_modules/react-dom/cjs/react-dom.development.js:20417:13)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:20346:9)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:20254:7)
      at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:20228:3)
      at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:20443:7)
      at Object.act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1161:27)
      at act (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:346:13)
      at Object.wrapAct [as render] (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:415:16)
      at new render (node_modules/enzyme/src/ReactWrapper.js:115:16)
      at mount (node_modules/enzyme/src/mount.js:10:10)
      at Suite.Object.<anonymous>.describe (src/__tests__/PostEditForm.js:25:19)
      at Object.describe (src/__tests__/PostEditForm.js:18:1)
````

**Comment by doke-v** [comment]
Your test is not running in a real browser, so it's a problem related to your testing environment. Configure jsdom to use canvas package or use some other library like jest-canvas-mock.
